Added CONTRIBUTING.md
OSCA-Kampala-Chapter/autotelegram pull request #57
Opened 2023-02-17 15:05 UTC by Samsonroyal

I created a new file, called CONTRIBUTING.md; and added all the necessary steps a developer can follow when wanting to contribute to this project. Please review the changes and merge the PR if it meets criteria.

2023-02-17 18:16 UTC, HassanBahati requested changes

2023-02-17 18:16 UTC, HassanBahati commented on CONTRIBUTING.md
> +3. Install the development dependencies using ` pip install -r requirements-dev.txt `
```suggestion
3. Install the development dependencies using ` pip install -r requirements.txt `

```

i think its [requirements.txt](https://github.com/OSCA-Kampala-Chapter/autotelegram/blob/main/requirements.txt) not `requirements-dev.txt`

2023-02-17 18:16 UTC, HassanBahati commented on CONTRIBUTING.md
> +1. Fork the Autotelegram repository on GitHub
```suggestion
1. Fork the [Autotelegram repository](https://github.com/OSCA-Kampala-Chapter/autotelegram) on GitHub

```

2023-02-17 18:16 UTC, HassanBahati commented on CONTRIBUTING.md
> +4. Read the <a href="https://osca-kampala-chapter.github.io/autotelegram/">documentation</a> to learn how to use the tool and how to run tests.
This doesn't seem to really get to address the `how to use the tool and how to write tests`.....as it the link leads to `documentation home page`....what that link lead to [TESTS.md](https://github.com/OSCA-Kampala-Chapter/autotelegram/pull/57/files#diff-6129e4842294d2f7cbef7f74cda4f4457150fa9c642210659bffbdb51c092994) which this PR adds?

2023-02-17 18:17 UTC, HassanBahati requested changes

2023-02-18 08:19 UTC, Samsonroyal commented on CONTRIBUTING.md
> +4. Read the <a href="https://osca-kampala-chapter.github.io/autotelegram/">documentation</a> to learn how to use the tool and how to run tests.
The documentation at the official autotelegram site is still under development and ideally, a user should be able to access all the necessary documentation from there once we've fully developed it. The TESTS.md has a very narrow scope

2023-02-18 23:13 UTC, ht-thomas commented
@Samsonroyal could you copy the content from CONTRIBUTING.md into docs/contributing.md instead. This is because that file is already linked to be automatically built with the docs. Also place the TESTS.md file in the docs folder,

2023-02-19 16:48 UTC, Samsonroyal commented
@ht-thomas let me do that then push new commits

2023-02-19 18:34 UTC, Samsonroyal commented
I am going to close this PR and open a new one where I have applied all the changes

2023-02-19 18:34 UTC, closed without merging